### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by pachakutek** [calxibe/StorjMonitor#18]
I tried following the Linux instructions on my mac, but it won't install. Is it supported on MacOS? Any different steps?

**Comment by pachakutek** [comment]
I was getting this error:

`StorjMonitor/storjMonitor.js:6
const dnode = require('dnode');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3`

And was able to resolve it by running on the terminal:
- Upgrading node.js (by _brew upgrade node_ - you need brew installed)
- Rebuilding npm (by _npm rebuild_ )
