### ISSUE TITLE
windows 7 32bit

### ISSUE THREAD

**Issue by webstavros** [calxibe/StorjMonitor#24]
hi im working with storj and i move a node to a windows 7 32bit system and your program is not working
can you verify that its only for 64bit systems or is there a work around that i can do to make it work of 32bit systems.
thanks in advance

**Comment by stefanbenten** [comment]
Hi!

You should be able to replace the node.exe file in the bin folder with the 32bit version, which you can download here:
https://nodejs.org/en/download/

Please give feedback if thats solves your problem!

**Comment by webstavros** [comment]
thanks for the link the change did not help... it came up with other errors now.. :(

**Comment by stefanbenten** [comment]
Just post them here and we can take a look!

**Comment by webstavros** [comment]
C:\Users\AcerOne\Downloads\StorjMonitor-master>bin\node.exe storjMonitor.js
C:\Users\AcerOne\Downloads\StorjMonitor-master\node_modules\bindings\bindings.js
:83
        throw e
        ^

Error: \\?\C:\Users\AcerOne\Downloads\StorjMonitor-master\node_modules\weak\buil
d\Release\weakref.node is not a valid Win32 application.
\\?\C:\Users\AcerOne\Downloads\StorjMonitor-master\node_modules\weak\build\Relea
se\weakref.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:683:18)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at bindings (C:\Users\AcerOne\Downloads\StorjMonitor-master\node_modules\bin
dings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\AcerOne\Downloads\StorjMonitor-master\node_m
odules\weak\lib\weak.js:7:35)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)

C:\Users\AcerOne\Downloads\StorjMonitor-master>pause
Press any key to continue . . .

**Comment by webstavros** [comment]
by the way im using the windows 7 **Starter** edition 32bit if that make any deference

**Comment by webstavros** [comment]
yes

**Comment by stefanbenten** [comment]
@webstavros By revisiting your issue did you already tried to rebuild the modules?
